version: '3.8'

services:
  redis:
    container_name: redis
    image: bitnami/redis:latest
    restart: always
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 300mb
    env_file:
      - .env
    ports:
      - ${PORT}:6379
    volumes:
      - ./volume:/bitnami/redis/data